### ISSUE TITLE
Remember volume %

### ISSUE THREAD

**Issue by omnigenous** [talwat/lowfi#11]
lowfi doesn't remember last set volume on relaunch.

**Comment by omnigenous** [comment]
Either `~/.config/lowfi/volume` or `~/.local/state/lowfi/volume` is good, not quiet sure which one is more fitting. I'm leaning towards `~/.config`.

Can't comment on second point, I'm for writing every time volume changes but I'm unaware if that may cause performance or any other type of issue.

**Comment by talwat** [comment]
Implemented with https://github.com/talwat/lowfi/commit/6b157dd457829d34524efd34043cc10e416bca17.
