### ISSUE TITLE
Option to hide control row

### ISSUE THREAD

**Issue by omnigenous** [talwat/lowfi#12]
I'm talking about last row inside a box:

`[s]kip [p]ause [q]uit`

A `--hide-controls` or similar flag should be sufficient. I want more minimalism :D

**Comment by talwat** [comment]
<img width="509" alt="Screenshot 2024-10-06 at 00 48 01" src="https://github.com/user-attachments/assets/2fee988d-703b-4f8c-8cd1-a0a00bbe4451">

Well... That was easy.

I'll probably be able to make a quick flag for it and then be done soon :)

**Comment by talwat** [comment]
Solved with https://github.com/talwat/lowfi/commit/baa2e095d9b165b05246db2551c275d115f99de8 👍
