### ISSUE TITLE
Got this issue after using Cargo install lowfi

### ISSUE THREAD

**Issue by tanaybhomia** [talwat/lowfi#2]
![image](https://github.com/user-attachments/assets/170616a2-6253-4e86-a16f-5aba68b510cc)

I have installed rust and cargo on my device.

**Comment by talwat** [comment]
Do you have ALSA? For some reason, the program isn't able to actually find it.

**Comment by sgob1** [comment]
This is solvable on ubuntu by installing `librust-alsa-sys-dev` and on Fedora by installing `rust-alsa+default-devel`.

**Comment by tanaybhomia** [comment]
How can fix this ? by just running the command ? I am sorry a newbie to Rust.

**Comment by talwat** [comment]
> This is solvable on ubuntu by installing `librust-alsa-sys-dev` and on Fedora by installing `rust-alsa+default-devel`.

Yup, this is the answer. You can also try `libasound2-dev`.
