### ISSUE TITLE
Player Flickering in Windows Terminal

### ISSUE THREAD

**Issue by aeburnett** [talwat/lowfi#26]
I am running the software and the audio sounds great but the player is flickering.

**Comment by talwat** [comment]
Yeah this seems to be a common issue with Windows Terminal. I could artificially lower the frame rate on windows to fix this, but it seems like it's just an abnormally slow terminal emulator.

I'll keep this issue in mind, but if anyone else has ideas feel free to chime in.

**Comment by talwat** [comment]
Resolved with https://github.com/talwat/lowfi/commit/a64b10e20cfee118d8942b6cae3b76ee35c33181 :)

Windows is a bit weird, and there also exists another bug with Inputs so I'll also have to fix that. Yay...

**Comment by talwat** [comment]
Well, I just fixed it, so this is resolved!
