### ISSUE TITLE
Failed to compile via cargo

### ISSUE THREAD

**Issue by gnarlin** [talwat/lowfi#27]
I'm on Ubuntu 24.04.1.
Installed libasound2-dev first.
Tried both: 
"cargo install lowfi --features mpris" and "cargo install lowfi" with the same results.

error[E0658]: `c".."` literals are experimental
   --> /home/gnarlin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lowfi-1.4.2/src/player.rs:112:20
    |
112 |         let mode = c"w".as_ptr();
    |                    ^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information

error[E0658]: `c".."` literals are experimental
   --> /home/gnarlin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lowfi-1.4.2/src/player.rs:118:26
    |
118 |         unsafe { freopen(c"/dev/null".as_ptr(), mode, stderr) };
    |                          ^^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information

error[E0658]: `c".."` literals are experimental
   --> /home/gnarlin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lowfi-1.4.2/src/player.rs:123:26
    |
123 |         unsafe { freopen(c"/dev/tty".as_ptr(), mode, stderr) };
    |                          ^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `lowfi` (bin "lowfi") due to 3 previous errors
error: failed to compile `lowfi v1.4.2`, intermediate artifacts can be found at `/tmp/cargo-installQzgnIy`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by talwat** [comment]
What's your rust version?

Also, if you don't need mpris then you can also just grab a binary from the releases.

**Comment by Sheldonimo** [comment]
Hi @gnarlin 
I encountered the exact same error, and in my case, I attempted a manual compilation of the repository.
my version of cargo is:
❯ cargo --version  
cargo 1.75.0

I was able to resolve the issue by making some changes in the file **src/player.rs**. First, I imported:

```rust
use std::ffi::CString;
```

Then:

```diff
- let mode = c"w".as_ptr();
+ let mode_cstring = CString::new("w").expect("CString::new failed");
+ let mode_ptr = mode_cstring.as_ptr();
```

```diff
- unsafe { freopen(c"/dev/null".as_ptr(), mode, stderr) };
+ let dev_null = CString::new("/dev/null").expect("CString::new failed");
+ let dev_null_ptr = dev_null.as_ptr();
+ unsafe { freopen(dev_null_ptr, mode_ptr, stderr); }
```

```diff
- unsafe { freopen(c"/dev/tty".as_ptr(), mode, stderr) };
+ let dev_tty = CString::new("/dev/tty").expect("CString::new failed");
+ let dev_tty_ptr = dev_tty.as_ptr();
+ unsafe { freopen(dev_tty_ptr, mode_ptr, stderr); }
```

By implementing these modifications, I was able to compile successfully. I am not sure if this is related to version discrepancies, but I performed the compilation using the latest commit from the main branch.

**Comment by talwat** [comment]
I didn't know cstrings were a new feature, so I'll probably implement this patch into main shortly.
