### ISSUE TITLE
not sound

### ISSUE THREAD

**Issue by Bryan-Campuzano** [talwat/lowfi#28]
![image](https://github.com/user-attachments/assets/ba50f9f9-e91e-4548-a5bd-3771493f48b2)
the app does not sound, i try to see the app on the sound control and does not appears, the install process was fine but just not playing music T-T

**Comment by danielwerg** [comment]
Do you have pipewire-alsa installed? I have no issues with this stack:

```
pipewire
pipewire-alsa
pipewire-audio
pipewire-jack
pipewire-pulse
wireplumber
```

**Comment by danielwerg** [comment]
https://github.com/talwat/lowfi#dependencies

**Comment by talwat** [comment]
I'm closing this since it's probably a dependency issue.
