### ISSUE TITLE
Bottom controls bar is not reflecting play/pause state in the play/pause control

### ISSUE THREAD

**Issue by paatre** [talwat/lowfi#29]
## Environment information

OS: Ubuntu 24.04
Version: lowfi 1.4.2

## Details

In `src/player/ui/components.rs`, controls are handled by the following function:

```rs
/// Creates the bottom controls bar, and also spaces it properly.
pub fn controls(width: usize) -> String {
    let controls = [["[s]", "kip"], ["[p]", "ause"], ["[q]", "uit"]];
    let len: usize = controls.concat().iter().map(|x| x.len()).sum();
    let controls = controls.map(|x| format!("{}{}", x[0].bold(), x[1]));

    controls.join(&" ".repeat((width - len) / (controls.len() - 1)))
}
```

The function defines all controls as hardcoded values:

```rs
let controls = [["[s]", "kip"], ["[p]", "ause"], ["[q]", "uit"]];`
```

The function doesn't do any handling of the play/pause state so that it could dynamically decide if  `[p]lay` or `[p]ause` control should be displayed.

**Comment by paatre** [comment]
Create a pull request: https://github.com/talwat/lowfi/pull/31.

**Comment by talwat** [comment]
Resolved with #31.

**Comment by talwat** [comment]
On second thought, after actually testing lowfi with this, I think I might revert the commit.

It's pretty universal that if you press the pause button while the player is still paused, it'll play. So for now I'll leave it out of the next release.

**Comment by Nindaleth** [comment]
Hi. I'm not sure if my thing is related or should be its own isue - $SUBJECT but for the MPRIS indicator.

That one always displays a "play" button even if clicking it cycles between playing and not playing state.

**Comment by talwat** [comment]
Hi @Nindaleth! I've gone ahead and made an issue for this https://github.com/talwat/lowfi/issues/37, since from a technical POV it is a separate issue.
