### ISSUE TITLE
Feature request: Add some system to adjust the volume

### ISSUE THREAD

**Issue by Samsu-F** [talwat/lowfi#3]
Being able to adjust the volume of this program directly in the terminal UI would be very helpful. Maybe a volume percentage changeable with the + and - keys or a slider controllable with the arrow keys?

**Comment by BrendanMesters** [comment]
I currently have a PR ( #4 ) open for this.

I'd advice you to wait till its merged to this repo though.

**Comment by talwat** [comment]
Solved with #4 :)
