### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by Th4nhTh4nh** [talwat/lowfi#30]
I'm stuck on loading for a long time when starting up, sometimes it takes a long time to load (or freezes) when switching to a new song. 
What can I do to make it load faster?
![Shot-2024-10-15-153137](https://github.com/user-attachments/assets/61dd2fda-362a-4430-ae88-ae4341c526be)
![Shot-2024-10-15-155845](https://github.com/user-attachments/assets/fecf97bd-eb92-4596-888a-37313c37a633)

**Comment by talwat** [comment]
Yeah, this makes sense, since it buffers entire songs rather than individual parts. This makes more sense with music files since they're relatively tiny. What's your download speed?

**Comment by Th4nhTh4nh** [comment]
Well, the speedtest results show a download speed of around 92 Mbps.
![Shot-2024-10-15-203820](https://github.com/user-attachments/assets/8f882d94-0e13-4788-9b0a-d9816a1e615a)

**Comment by talwat** [comment]
You could try updating, since 1.5.0 overhauled a lot of networking & buffering code, but if that also doesn't help then try to send a video.

**Comment by Rudra-241** [comment]
i am having the same issue, it is stuck at loading for me.

**Comment by talwat** [comment]
Did you try the manual method? It could be related to mpris perhaps?

**Comment by talwat** [comment]
I can't seem to reproduce this issue. I'll reopen it if this issue is still prevalent on 1.5.0+.

**Comment by Rudra-241** [comment]
Sorry for the delayed response, it is working perfectly for me after i installed it using cargo install with mpris.

**Comment by tqwewe** [comment]
I'm trying to run lowfi on my mac, and it seems to be stuck saying "loading" forever. My internet is fast, and after waiting a long time nothing happens. I assume somethings broken.. sadly I can't use lowfi

**Comment by danielwerg** [comment]
@tqwewe lowfi preload 5 tracks at the time (can be tweaked with `-s|--buffer-size` flag), how fast does https://lofigirl.com/wp-content/uploads/2022/11/001-The-Descent.mp3 load in your browser or via mpv?

**Comment by tqwewe** [comment]
It loaded in my browser in under 2 seconds. Pretty sure somethings definitely wrong with lowfi for me, not sure if its OSX specific.
