### ISSUE TITLE
Missing dependency in installation instructions for linux

### ISSUE THREAD

**Issue by henioStraszny** [talwat/lowfi#32]
In order to install it on Debian, `libssl-dev` is needed in addition to `libasound2-dev`, I've prepared small change in docs, but it seems that I cannot create PR here.

Here is modified section in `README.md`

```
### Dependencies

You'll need Rust 1.74.0+.

On MacOS & Windows, no extra dependencies are needed.

On Linux, you'll also need alsa and openssl and it's headers (`alsa-lib` on Arch,
`libasound2-dev`,`libssl-dev` on Ubuntu/Debian). Make sure to also install `pulseaudio-alsa`
if you're using pulseaudio.
```

**Comment by talwat** [comment]
Huh, I actually thought most systems would have it by default because of `cargo`. I'll update it soon.

**Comment by talwat** [comment]
Fixed with https://github.com/talwat/lowfi/commit/120ac3f972ef0b24efaeca9bb5b6f50b4c41c0ef.

**Comment by henioStraszny** [comment]
Actually I've tested that on Debian which should be similar to Ubuntu, so you might add in readme **Ubuntu/Debian**
