### ISSUE TITLE
[Bug] Pressing p pauses and immediately unpauses

### ISSUE THREAD

**Issue by astra1dev** [talwat/lowfi#33]
- **System info:** Windows 11 23H2, latest Windows Terminal version

- **Description:** When i press `p` to pause the track, it pauses for a brief moment and then unpauses. This doesn't change no matter how long i press `p`. 

- **Expected behaviour:** Simply pause or unpause the track

I suspect this is because it detects me pressing `p` and then keeps listening instead of waiting for me to release the key. 
I would create a pull request but I'm still new to rust and don't just want to use chatGPT 😅

Let me know if you need more information.
Have a nice day!

**Comment by talwat** [comment]
Yeah, I think this is a case of Windows tomfoolery. I can't precisely control input since it's just whatever input the terminal gets, so either it's a bug in the terminal you're using, or in crossterm. I'll try debugging it myself though to see, since I have a Windows VM.
