### ISSUE TITLE
Multiple instances of lowfi with MPRIS?

### ISSUE THREAD

**Issue by danielwerg** [talwat/lowfi#40]
Currently lowfi with MPRIS just exits silently (or prints "bye! :)" when `-a` flag is passed) when another instance of lowfi is present.

Now we [Custom Track Lists](https://github.com/talwat/lowfi#custom-track-lists) I need it more then ever.

**Comment by talwat** [comment]
This could possibly be an MPRIS problem. Could you try without MPRIS and see if it works with multiple instances?

**Comment by danielwerg** [comment]
Yep, confirmed. Issue with mpris implementation.

**Comment by talwat** [comment]
Well, it sort of makes sense, I mean having two instances of lowfi both with the same MPRIS label seems pretty strange.

I'll test a couple of things, although I'm still a bit confused on why anyone would want to have multiple instances of lowfi running at the same time with MPRIS.

**Comment by danielwerg** [comment]
This is how multiple instances of mpv looks like:

```sh
mpv.instance8369
mpv.instance8347
mpv.instance8364
mpv # <- first instance
mpv.instance8472
mpv.instance8526
mpv.instance8471
```

KDE connect appends long (maybe UUID? can't remember) to each instance.

For my use case I would put two or more lowfi's on my second monitor, where first one would play normal lofigirl playlist and second one my custom track list. Then I would switch between the two depending on the mood. I exclusively use lowfi with MPRIS. It is much easier than selecting window in my second monitor especially because I have a script to easily cycle MPRIS players, so it's only take me two key press combinations.

**Comment by talwat** [comment]
Ohh alright, I'll see if I can integrate that into lowfi.

Is the numbering based on the PID for mpv?

**Comment by danielwerg** [comment]
Yeah, mpv uses pid for second and onward instances.

Ideally lowfi instance would include custom tracklist file name if `--tracks` flag is passed to make it easily identifiable. If it's not too much hassle to implement, of course.

**Comment by talwat** [comment]
I've got this so far:

```txt
lowfi.lofigirl.instance36667
lowfi.micropop.instance37037
```

Which I think is fine, since checking whether there are other MPRIS players running is much more involved.
Let me know what you think.

**Comment by danielwerg** [comment]
Looks great! I can easily shorten `instancePID` part in my player picker script, like I do with firefox (`firefox.instance_1_21` -> `Firefox.._21`)

**Comment by talwat** [comment]
Awesome :)

I'm just doing "instanceX" since that appears to be the mostly universal standard.

I'll go ahead and close this, and a new release should be out pretty soon. Let me know if I made any other stupid mistakes :^)

**Comment by danielwerg** [comment]
Love it! Haven't spotted any issue so far.
