### ISSUE TITLE
[issue ]how to run without tui in the background?

### ISSUE THREAD

**Issue by sh1zicus** [talwat/lowfi#42]
I want to add a button to the ags config (hyprland)
I didn’t find anything similar,

 and I only need the ```lowfi --start and --stop``` commands

**Comment by talwat** [comment]
Do you mean *controlling* lowfi from a hyprland button?

If so, lowfi supports MPRIS so you can use [playerctl](https://github.com/altdesktop/playerctl)

**Comment by danielwerg** [comment]
Put terminal with lowfi in special workspace and use `playerctl --player lowfi play` or `pause`

**Comment by s0mesh1t** [comment]
> Do you mean _controlling_ lowfi from a hyprland button?
> 
> If so, lowfi supports MPRIS so you can use [playerctl](https://github.com/altdesktop/playerctl).

I just want to run it in the background so it won't be visible

**Comment by danielwerg** [comment]
@s0mesh1t Did you see [my comment](https://github.com/talwat/lowfi/issues/42#issuecomment-2449705808)? If you never want to see it don't use special workspace and just start it with `exec-once` in hyprland config.

**Comment by talwat** [comment]
Closing as (probably) answered.

If you really want it in the background, there are ways such as using hyprland or `&`.
