### ISSUE TITLE
Feature request: Add optional flag to set player width in columns

### ISSUE THREAD

**Issue by jjpprr** [talwat/lowfi#44]
I appreciate the default small size but with the number of character columns many songs have rather long names that end up showing with ellipsis at the end.

It would be nice to have a flag allowing to set the number of columns for the player.

**Comment by talwat** [comment]
I might be able to add some sort of arbitrary unit, but because of the way lowfi is rendered it might make some things difficult such as with the control bar.

**Comment by talwat** [comment]
Resolved with https://github.com/talwat/lowfi/commit/a6f3eb034de7fa41fdf64b6cc499bbfdd2106622.
