### ISSUE TITLE
High frequent blinking in powershell

### ISSUE THREAD

**Issue by bjornasm** [talwat/lowfi#6]
Not the largest issue, but there is a constant high frequent blinking of the TUI. Also the pause button is not working. 

Lowfi v1.2.3
rustc 1.81.0 
PSVersion 7.4.5

Pause button does not work, but there is no blinking in CMD. Note that I use oh-my-posh, if that could have any impact.

**Comment by talwat** [comment]
Are you using `p` for pause? The actual physical button hasn't been implemented yet.

Also, about the blinking, it is somewhat related to your Terminal speed, so you might have to use a faster terminal. Although, I could add an `fps` flag to make the user capable of making adjustments.

**Comment by talwat** [comment]
I'm gonna close this for now, since it's an isolated case from the looks of it, but I might return to it later for the `fps` flag.
