### ISSUE TITLE
error: failed to run custom build command for `alsa-sys v0.3.1`

### ISSUE THREAD

**Issue by mlliarm** [talwat/lowfi#9]
Hello !

### Error

Got this error during `cargo install lowfi`:

![Screenshot_2024-10-03_21-57-49](https://github.com/user-attachments/assets/005ce7a9-8e02-4bfb-ba00-25918d7d8e8d)

### Specs

My system specs:

```
$ cargo --version
cargo 1.78.0 (54d8815d0 2024-03-26)

$ sudo lsb_release -a
Description: Debian GNU/Linux 11 (bullseye)

$ uname -a
Linux <name> 5.10.0-32-amd64
```

### Related

- https://stackoverflow.com/a/75960396
- https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md
- https://github.com/RustAudio/rodio/issues/538#issuecomment-1890866670

### Fix

Just install the missing alsa dependencies & rerun cargo build:

```
$ sudo apt install libasound2-dev libudev-dev
$ PKG_CONFIG_PATH=/tmp/cargo-install98RCMj
/path/to/lowfi$ cargo install lowfi
```

Note: The third related link just mentions `libasound2-dev`; it could be the case that only this missing library was necessary.

**Comment by mlliarm** [comment]
As it's fixed, I'll close it.

Wanted just to report it.

Perhaps you'd like to add some OS dependencies in the README.md :) ! Cheers !

**Comment by talwat** [comment]
> Perhaps you'd like to add some OS dependencies in the README.md :) ! Cheers !

Will do, sorry!
